{{- if .Values.backup.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hermes.fullname" . }}-store-backup
  labels:
    app: {{ template "hermes.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  aws-access-key-id: {{ .Values.backup.awsaccesskey }}
  aws-secret-access-key: {{ .Values.backup.awssecretaccesskey }}
  s3-url: {{ .Values.backup.s3url }}
  slack-channel: {{ .Values.backup.slackchannel }}
  slack-url: {{ .Values.backup.slackurl }}
{{- end }}
