{{- if .Values.backup.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "hermes.fullname" . }}-store-backup
  labels:
    app: {{ template "hermes.name" . }}
    role: {{ template "hermes.role" . }}-store-backup
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.backup.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "hermes.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "hermes.name" . }}
        role: {{ template "hermes.role" . }}-store-backup
    spec:
      affinity:
{{ toYaml ( default .Values.global.affinity .Values.backup.affinity ) | indent 8 }}
      containers:
      - env:
        - name: APP_ENVIRONMENT
          value: {{ .Values.backup.env }}
        - name: STORE_SERVICE
          value: {{ .Release.Name }}-{{ .Values.redis.nameOverride }}:{{ .Values.redis.port }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-{{ .Values.redis.nameOverride }}
              key: redis-password
        - name: S3_URL
          valueFrom:
            secretKeyRef:
              key: s3-url
              name: {{ template "hermes.fullname" . }}-store-backup
        - name: SLACK_CHANNEL
          valueFrom:
            secretKeyRef:
              key: slack-channel
              name: {{ template "hermes.fullname" . }}-store-backup
        - name: SLACK_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              key: slack-url
              name: {{ template "hermes.fullname" . }}-store-backup
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: aws-access-key-id
              name: {{ template "hermes.fullname" . }}-store-backup
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: aws-secret-access-key
              name: {{ template "hermes.fullname" . }}-store-backup
        image: {{ .Values.backup.image }}:{{ .Values.backup.tag }}
        imagePullPolicy: Always
        name: {{ .Chart.Name }}-store-backup
      imagePullSecrets:
      - name: docker-registry
      restartPolicy: Always
{{- end }}
