apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hermes.fullname" . }}
  labels:
    app: {{ template "hermes.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if .Values.cfapi.token }}
  cfapi-token: {{ .Values.cfapi.token | b64enc | quote }}
  {{- else}}
  cfapi-token: {{ ""  | b64enc | quote }}
  {{- end }}