# Default values for hermes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

# use SemVer image tag without PATCH numver
image:
  repository: codefresh/hermes
  tag: 0.9
  pullPolicy: IfNotPresent

service:
  name: hermes
  type: ClusterIP
  externalPort: 80
  internalPort: 8080

# override redis service name to 'store'
redis:
  nameOverride: store
  port: 6379
  redisExtraFlags: "--appendonly no"

# set log level
logLevel: debug

# set log format to Codefresh JSON
logJSON: true

# configure cfapi access
cfapi:
## cfapi.token - get it from Codefresh application
##
# token:

## cfapi.service - service name (default: {{.Release.Name}}-cfapi)
## cfapi.protocol - http/https (default to http)
## cfapi.port - access port (default to 3000)
##
#  service:

## cfapi.protocol - http/https (default to http)
##
  protocol: http

## cfapi.port - access port (default to 3000)
##
  port: 3000

ingress:
  enabled: false
  # Used to create an Ingress record.
  hosts:
    - hermes.local
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
backup:
  replicaCount: 1
  image: codefresh/hermes-store-backup
  tag: 0.1.2
  env: production
global:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nodeType
            operator: NotIn
            values:
            - internal
            - worker
